// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/cloudbuild/v1/cloudbuild.proto

package com.google.cloudbuild.v1;

public interface CreateWorkerPoolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.cloudbuild.v1.CreateWorkerPoolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the parent project.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * ID of the parent project.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * `WorkerPool` resource to create.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 2;</code>
   * @return Whether the workerPool field is set.
   */
  boolean hasWorkerPool();
  /**
   * <pre>
   * `WorkerPool` resource to create.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 2;</code>
   * @return The workerPool.
   */
  com.google.cloudbuild.v1.WorkerPool getWorkerPool();
  /**
   * <pre>
   * `WorkerPool` resource to create.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 2;</code>
   */
  com.google.cloudbuild.v1.WorkerPoolOrBuilder getWorkerPoolOrBuilder();
}
