// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/cloudbuild/v1/cloudbuild.proto

package com.google.cloudbuild.v1;

public interface DeleteWorkerPoolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.cloudbuild.v1.DeleteWorkerPoolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The field will contain name of the resource requested, for example:
   * "projects/project-1/workerPools/workerpool-name"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The field will contain name of the resource requested, for example:
   * "projects/project-1/workerPools/workerpool-name"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
