// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/cloudbuild/v1/cloudbuild.proto

package com.google.cloudbuild.v1;

public interface UpdateWorkerPoolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.cloudbuild.v1.UpdateWorkerPoolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The field will contain name of the resource requested, for example:
   * "projects/project-1/workerPools/workerpool-name"
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The field will contain name of the resource requested, for example:
   * "projects/project-1/workerPools/workerpool-name"
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * `WorkerPool` resource to update.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 3;</code>
   * @return Whether the workerPool field is set.
   */
  boolean hasWorkerPool();
  /**
   * <pre>
   * `WorkerPool` resource to update.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 3;</code>
   * @return The workerPool.
   */
  com.google.cloudbuild.v1.WorkerPool getWorkerPool();
  /**
   * <pre>
   * `WorkerPool` resource to update.
   * </pre>
   *
   * <code>.google.devtools.cloudbuild.v1.WorkerPool worker_pool = 3;</code>
   */
  com.google.cloudbuild.v1.WorkerPoolOrBuilder getWorkerPoolOrBuilder();
}
