/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/cloudbuild/v1/cloudbuild.proto

package com.google.cloudbuild.v1;

public final class Cloudbuild {
  private Cloudbuild() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_RetryBuildRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_RetryBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_RunBuildTriggerRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_RunBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_StorageSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_RepoSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_RepoSource_SubstitutionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Source_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Source_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuiltImage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Volume_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Volume_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Results_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Results_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_ArtifactResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ArtifactResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Build_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Build_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Build_TimingEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Build_TimingEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Artifacts_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Artifacts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Artifacts_ArtifactObjects_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_TimeSpan_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_TimeSpan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_FileHashes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Hash_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Hash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Secret_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Secret_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_Secret_SecretEnvEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_Secret_SecretEnvEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_GitHubEventsConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_GitHubEventsConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_PullRequestFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_PullRequestFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_PushFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_PushFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_cloudbuild_v1_BuildOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n.google/devtools/cloudbuild/v1/cloudbui"
          + "ld.proto\022\035google.devtools.cloudbuild.v1\032"
          + "\034google/api/annotations.proto\032\027google/ap"
          + "i/client.proto\032\037google/api/field_behavio"
          + "r.proto\032\031google/api/resource.proto\032#goog"
          + "le/longrunning/operations.proto\032\036google/"
          + "protobuf/duration.proto\032\033google/protobuf"
          + "/empty.proto\032 google/protobuf/field_mask"
          + ".proto\032\037google/protobuf/timestamp.proto\""
          + "=\n\021RetryBuildRequest\022\027\n\nproject_id\030\001 \001(\t"
          + "B\003\340A\002\022\017\n\002id\030\002 \001(\tB\003\340A\002\"\212\001\n\026RunBuildTrigg"
          + "erRequest\022\027\n\nproject_id\030\001 \001(\tB\003\340A\002\022\027\n\ntr"
          + "igger_id\030\002 \001(\tB\003\340A\002\022>\n\006source\030\003 \001(\0132).go"
          + "ogle.devtools.cloudbuild.v1.RepoSourceB\003"
          + "\340A\002\"C\n\rStorageSource\022\016\n\006bucket\030\001 \001(\t\022\016\n\006"
          + "object\030\002 \001(\t\022\022\n\ngeneration\030\003 \001(\003\"\256\002\n\nRep"
          + "oSource\022\022\n\nproject_id\030\001 \001(\t\022\021\n\trepo_name"
          + "\030\002 \001(\t\022\025\n\013branch_name\030\003 \001(\tH\000\022\022\n\010tag_nam"
          + "e\030\004 \001(\tH\000\022\024\n\ncommit_sha\030\005 \001(\tH\000\022\013\n\003dir\030\007"
          + " \001(\t\022\024\n\014invert_regex\030\010 \001(\010\022S\n\rsubstituti"
          + "ons\030\t \003(\0132<.google.devtools.cloudbuild.v"
          + "1.RepoSource.SubstitutionsEntry\0324\n\022Subst"
          + "itutionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
          + "\t:\0028\001B\n\n\010revision\"\234\001\n\006Source\022F\n\016storage_"
          + "source\030\002 \001(\0132,.google.devtools.cloudbuil"
          + "d.v1.StorageSourceH\000\022@\n\013repo_source\030\003 \001("
          + "\0132).google.devtools.cloudbuild.v1.RepoSo"
          + "urceH\000B\010\n\006source\"m\n\nBuiltImage\022\014\n\004name\030\001"
          + " \001(\t\022\016\n\006digest\030\003 \001(\t\022A\n\013push_timing\030\004 \001("
          + "\0132\'.google.devtools.cloudbuild.v1.TimeSp"
          + "anB\003\340A\003\"\256\003\n\tBuildStep\022\014\n\004name\030\001 \001(\t\022\013\n\003e"
          + "nv\030\002 \003(\t\022\014\n\004args\030\003 \003(\t\022\013\n\003dir\030\004 \001(\t\022\n\n\002i"
          + "d\030\005 \001(\t\022\020\n\010wait_for\030\006 \003(\t\022\022\n\nentrypoint\030"
          + "\007 \001(\t\022\022\n\nsecret_env\030\010 \003(\t\0226\n\007volumes\030\t \003"
          + "(\0132%.google.devtools.cloudbuild.v1.Volum"
          + "e\022<\n\006timing\030\n \001(\0132\'.google.devtools.clou"
          + "dbuild.v1.TimeSpanB\003\340A\003\022A\n\013pull_timing\030\r"
          + " \001(\0132\'.google.devtools.cloudbuild.v1.Tim"
          + "eSpanB\003\340A\003\022*\n\007timeout\030\013 \001(\0132\031.google.pro"
          + "tobuf.Duration\022@\n\006status\030\014 \001(\0162+.google."
          + "devtools.cloudbuild.v1.Build.StatusB\003\340A\003"
          + "\"$\n\006Volume\022\014\n\004name\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\"\357"
          + "\001\n\007Results\0229\n\006images\030\002 \003(\0132).google.devt"
          + "ools.cloudbuild.v1.BuiltImage\022\031\n\021build_s"
          + "tep_images\030\003 \003(\t\022\031\n\021artifact_manifest\030\004 "
          + "\001(\t\022\025\n\rnum_artifacts\030\005 \001(\003\022\032\n\022build_step"
          + "_outputs\030\006 \003(\014\022@\n\017artifact_timing\030\007 \001(\0132"
          + "\'.google.devtools.cloudbuild.v1.TimeSpan"
          + "\"`\n\016ArtifactResult\022\020\n\010location\030\001 \001(\t\022<\n\t"
          + "file_hash\030\002 \003(\0132).google.devtools.cloudb"
          + "uild.v1.FileHashes\"\362\013\n\005Build\022\017\n\002id\030\001 \001(\t"
          + "B\003\340A\003\022\027\n\nproject_id\030\020 \001(\tB\003\340A\003\022@\n\006status"
          + "\030\002 \001(\0162+.google.devtools.cloudbuild.v1.B"
          + "uild.StatusB\003\340A\003\022\032\n\rstatus_detail\030\030 \001(\tB"
          + "\003\340A\003\0225\n\006source\030\003 \001(\0132%.google.devtools.c"
          + "loudbuild.v1.Source\0227\n\005steps\030\013 \003(\0132(.goo"
          + "gle.devtools.cloudbuild.v1.BuildStep\022<\n\007"
          + "results\030\n \001(\0132&.google.devtools.cloudbui"
          + "ld.v1.ResultsB\003\340A\003\0224\n\013create_time\030\006 \001(\0132"
          + "\032.google.protobuf.TimestampB\003\340A\003\0223\n\nstar"
          + "t_time\030\007 \001(\0132\032.google.protobuf.Timestamp"
          + "B\003\340A\003\0224\n\013finish_time\030\010 \001(\0132\032.google.prot"
          + "obuf.TimestampB\003\340A\003\022*\n\007timeout\030\014 \001(\0132\031.g"
          + "oogle.protobuf.Duration\022\016\n\006images\030\r \003(\t\022"
          + ",\n\tqueue_ttl\030( \001(\0132\031.google.protobuf.Dur"
          + "ation\022;\n\tartifacts\030% \001(\0132(.google.devtoo"
          + "ls.cloudbuild.v1.Artifacts\022\023\n\013logs_bucke"
          + "t\030\023 \001(\t\022O\n\021source_provenance\030\025 \001(\0132/.goo"
          + "gle.devtools.cloudbuild.v1.SourceProvena"
          + "nceB\003\340A\003\022\035\n\020build_trigger_id\030\026 \001(\tB\003\340A\003\022"
          + "<\n\007options\030\027 \001(\0132+.google.devtools.cloud"
          + "build.v1.BuildOptions\022\024\n\007log_url\030\031 \001(\tB\003"
          + "\340A\003\022N\n\rsubstitutions\030\035 \003(\01327.google.devt"
          + "ools.cloudbuild.v1.Build.SubstitutionsEn"
          + "try\022\014\n\004tags\030\037 \003(\t\0226\n\007secrets\030  \003(\0132%.goo"
          + "gle.devtools.cloudbuild.v1.Secret\022E\n\006tim"
          + "ing\030! \003(\01320.google.devtools.cloudbuild.v"
          + "1.Build.TimingEntryB\003\340A\003\022\027\n\017service_acco"
          + "unt\030* \001(\t\0324\n\022SubstitutionsEntry\022\013\n\003key\030\001"
          + " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032V\n\013TimingEntry\022\013"
          + "\n\003key\030\001 \001(\t\0226\n\005value\030\002 \001(\0132\'.google.devt"
          + "ools.cloudbuild.v1.TimeSpan:\0028\001\"\214\001\n\006Stat"
          + "us\022\022\n\016STATUS_UNKNOWN\020\000\022\n\n\006QUEUED\020\001\022\013\n\007WO"
          + "RKING\020\002\022\013\n\007SUCCESS\020\003\022\013\n\007FAILURE\020\004\022\022\n\016INT"
          + "ERNAL_ERROR\020\005\022\013\n\007TIMEOUT\020\006\022\r\n\tCANCELLED\020"
          + "\007\022\013\n\007EXPIRED\020\t:\177\352A|\n\037cloudbuild.googleap"
          + "is.com/Build\022!projects/{project}/builds/"
          + "{build}\0226projects/{project}/locations/{l"
          + "ocation}/builds/{build}\"\330\001\n\tArtifacts\022\016\n"
          + "\006images\030\001 \003(\t\022I\n\007objects\030\002 \001(\01328.google."
          + "devtools.cloudbuild.v1.Artifacts.Artifac"
          + "tObjects\032p\n\017ArtifactObjects\022\020\n\010location\030"
          + "\001 \001(\t\022\r\n\005paths\030\002 \003(\t\022<\n\006timing\030\003 \001(\0132\'.g"
          + "oogle.devtools.cloudbuild.v1.TimeSpanB\003\340"
          + "A\003\"h\n\010TimeSpan\022.\n\nstart_time\030\001 \001(\0132\032.goo"
          + "gle.protobuf.Timestamp\022,\n\010end_time\030\002 \001(\013"
          + "2\032.google.protobuf.Timestamp\"M\n\026BuildOpe"
          + "rationMetadata\0223\n\005build\030\001 \001(\0132$.google.d"
          + "evtools.cloudbuild.v1.Build\"\343\002\n\020SourcePr"
          + "ovenance\022M\n\027resolved_storage_source\030\003 \001("
          + "\0132,.google.devtools.cloudbuild.v1.Storag"
          + "eSource\022G\n\024resolved_repo_source\030\006 \001(\0132)."
          + "google.devtools.cloudbuild.v1.RepoSource"
          + "\022Y\n\013file_hashes\030\004 \003(\0132?.google.devtools."
          + "cloudbuild.v1.SourceProvenance.FileHashe"
          + "sEntryB\003\340A\003\032\\\n\017FileHashesEntry\022\013\n\003key\030\001 "
          + "\001(\t\0228\n\005value\030\002 \001(\0132).google.devtools.clo"
          + "udbuild.v1.FileHashes:\0028\001\"D\n\nFileHashes\022"
          + "6\n\tfile_hash\030\001 \003(\0132#.google.devtools.clo"
          + "udbuild.v1.Hash\"|\n\004Hash\022:\n\004type\030\001 \001(\0162,."
          + "google.devtools.cloudbuild.v1.Hash.HashT"
          + "ype\022\r\n\005value\030\002 \001(\014\")\n\010HashType\022\010\n\004NONE\020\000"
          + "\022\n\n\006SHA256\020\001\022\007\n\003MD5\020\002\"\232\001\n\006Secret\022\024\n\014kms_"
          + "key_name\030\001 \001(\t\022H\n\nsecret_env\030\003 \003(\01324.goo"
          + "gle.devtools.cloudbuild.v1.Secret.Secret"
          + "EnvEntry\0320\n\016SecretEnvEntry\022\013\n\003key\030\001 \001(\t\022"
          + "\r\n\005value\030\002 \001(\014:\0028\001\"g\n\022CreateBuildRequest"
          + "\022\027\n\nproject_id\030\001 \001(\tB\003\340A\002\0228\n\005build\030\002 \001(\013"
          + "2$.google.devtools.cloudbuild.v1.BuildB\003"
          + "\340A\002\";\n\017GetBuildRequest\022\027\n\nproject_id\030\001 \001"
          + "(\tB\003\340A\002\022\017\n\002id\030\002 \001(\tB\003\340A\002\"c\n\021ListBuildsRe"
          + "quest\022\027\n\nproject_id\030\001 \001(\tB\003\340A\002\022\021\n\tpage_s"
          + "ize\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\022\016\n\006filter\030"
          + "\010 \001(\t\"c\n\022ListBuildsResponse\0224\n\006builds\030\001 "
          + "\003(\0132$.google.devtools.cloudbuild.v1.Buil"
          + "d\022\027\n\017next_page_token\030\002 \001(\t\">\n\022CancelBuil"
          + "dRequest\022\027\n\nproject_id\030\001 \001(\tB\003\340A\002\022\017\n\002id\030"
          + "\002 \001(\tB\003\340A\002\"\215\005\n\014BuildTrigger\022\017\n\002id\030\001 \001(\tB"
          + "\003\340A\003\022\023\n\013description\030\n \001(\t\022\014\n\004name\030\025 \001(\t\022"
          + "\014\n\004tags\030\023 \003(\t\022C\n\020trigger_template\030\007 \001(\0132"
          + ").google.devtools.cloudbuild.v1.RepoSour"
          + "ce\022A\n\006github\030\r \001(\01321.google.devtools.clo"
          + "udbuild.v1.GitHubEventsConfig\0225\n\005build\030\004"
          + " \001(\0132$.google.devtools.cloudbuild.v1.Bui"
          + "ldH\000\022\022\n\010filename\030\010 \001(\tH\000\0224\n\013create_time\030"
          + "\005 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022\020"
          + "\n\010disabled\030\t \001(\010\022U\n\rsubstitutions\030\013 \003(\0132"
          + ">.google.devtools.cloudbuild.v1.BuildTri"
          + "gger.SubstitutionsEntry\022\025\n\rignored_files"
          + "\030\017 \003(\t\022\026\n\016included_files\030\020 \003(\t\0324\n\022Substi"
          + "tutionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
          + ":\0028\001:R\352AO\n&cloudbuild.googleapis.com/Bui"
          + "ldTrigger\022%projects/{project}/triggers/{"
          + "trigger}B\020\n\016build_template\"\334\001\n\022GitHubEve"
          + "ntsConfig\022\033\n\017installation_id\030\001 \001(\003B\002\030\001\022\r"
          + "\n\005owner\030\006 \001(\t\022\014\n\004name\030\007 \001(\t\022H\n\014pull_requ"
          + "est\030\004 \001(\01320.google.devtools.cloudbuild.v"
          + "1.PullRequestFilterH\000\0229\n\004push\030\005 \001(\0132).go"
          + "ogle.devtools.cloudbuild.v1.PushFilterH\000"
          + "B\007\n\005event\"\337\001\n\021PullRequestFilter\022\020\n\006branc"
          + "h\030\002 \001(\tH\000\022X\n\017comment_control\030\005 \001(\0162?.goo"
          + "gle.devtools.cloudbuild.v1.PullRequestFi"
          + "lter.CommentControl\022\024\n\014invert_regex\030\006 \001("
          + "\010\"=\n\016CommentControl\022\025\n\021COMMENTS_DISABLED"
          + "\020\000\022\024\n\020COMMENTS_ENABLED\020\001B\t\n\007git_ref\"N\n\nP"
          + "ushFilter\022\020\n\006branch\030\002 \001(\tH\000\022\r\n\003tag\030\003 \001(\t"
          + "H\000\022\024\n\014invert_regex\030\004 \001(\010B\t\n\007git_ref\"w\n\031C"
          + "reateBuildTriggerRequest\022\027\n\nproject_id\030\001"
          + " \001(\tB\003\340A\002\022A\n\007trigger\030\002 \001(\0132+.google.devt"
          + "ools.cloudbuild.v1.BuildTriggerB\003\340A\002\"J\n\026"
          + "GetBuildTriggerRequest\022\027\n\nproject_id\030\001 \001"
          + "(\tB\003\340A\002\022\027\n\ntrigger_id\030\002 \001(\tB\003\340A\002\"Z\n\030List"
          + "BuildTriggersRequest\022\027\n\nproject_id\030\001 \001(\t"
          + "B\003\340A\002\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003"
          + " \001(\t\"s\n\031ListBuildTriggersResponse\022=\n\010tri"
          + "ggers\030\001 \003(\0132+.google.devtools.cloudbuild"
          + ".v1.BuildTrigger\022\027\n\017next_page_token\030\002 \001("
          + "\t\"M\n\031DeleteBuildTriggerRequest\022\027\n\nprojec"
          + "t_id\030\001 \001(\tB\003\340A\002\022\027\n\ntrigger_id\030\002 \001(\tB\003\340A\002"
          + "\"\220\001\n\031UpdateBuildTriggerRequest\022\027\n\nprojec"
          + "t_id\030\001 \001(\tB\003\340A\002\022\027\n\ntrigger_id\030\002 \001(\tB\003\340A\002"
          + "\022A\n\007trigger\030\003 \001(\0132+.google.devtools.clou"
          + "dbuild.v1.BuildTriggerB\003\340A\002\"\241\010\n\014BuildOpt"
          + "ions\022L\n\026source_provenance_hash\030\001 \003(\0162,.g"
          + "oogle.devtools.cloudbuild.v1.Hash.HashTy"
          + "pe\022Y\n\027requested_verify_option\030\002 \001(\01628.go"
          + "ogle.devtools.cloudbuild.v1.BuildOptions"
          + ".VerifyOption\022M\n\014machine_type\030\003 \001(\01627.go"
          + "ogle.devtools.cloudbuild.v1.BuildOptions"
          + ".MachineType\022\024\n\014disk_size_gb\030\006 \001(\003\022[\n\023su"
          + "bstitution_option\030\004 \001(\0162>.google.devtool"
          + "s.cloudbuild.v1.BuildOptions.Substitutio"
          + "nOption\022\035\n\025dynamic_substitutions\030\021 \001(\010\022\\"
          + "\n\024log_streaming_option\030\005 \001(\0162>.google.de"
          + "vtools.cloudbuild.v1.BuildOptions.LogStr"
          + "eamingOption\022\023\n\013worker_pool\030\007 \001(\t\022H\n\007log"
          + "ging\030\013 \001(\01627.google.devtools.cloudbuild."
          + "v1.BuildOptions.LoggingMode\022\013\n\003env\030\014 \003(\t"
          + "\022\022\n\nsecret_env\030\r \003(\t\0226\n\007volumes\030\016 \003(\0132%."
          + "google.devtools.cloudbuild.v1.Volume\".\n\014"
          + "VerifyOption\022\020\n\014NOT_VERIFIED\020\000\022\014\n\010VERIFI"
          + "ED\020\001\"C\n\013MachineType\022\017\n\013UNSPECIFIED\020\000\022\020\n\014"
          + "N1_HIGHCPU_8\020\001\022\021\n\rN1_HIGHCPU_32\020\002\"5\n\022Sub"
          + "stitutionOption\022\016\n\nMUST_MATCH\020\000\022\017\n\013ALLOW"
          + "_LOOSE\020\001\"G\n\022LogStreamingOption\022\022\n\016STREAM"
          + "_DEFAULT\020\000\022\r\n\tSTREAM_ON\020\001\022\016\n\nSTREAM_OFF\020"
          + "\002\"|\n\013LoggingMode\022\027\n\023LOGGING_UNSPECIFIED\020"
          + "\000\022\n\n\006LEGACY\020\001\022\014\n\010GCS_ONLY\020\002\022\030\n\020STACKDRIV"
          + "ER_ONLY\020\003\032\002\010\001\022\026\n\022CLOUD_LOGGING_ONLY\020\005\022\010\n"
          + "\004NONE\020\0042\321\021\n\nCloudBuild\022\305\001\n\013CreateBuild\0221"
          + ".google.devtools.cloudbuild.v1.CreateBui"
          + "ldRequest\032\035.google.longrunning.Operation"
          + "\"d\202\323\344\223\002)\" /v1/projects/{project_id}/buil"
          + "ds:\005build\332A\020project_id,build\312A\037\n\005Build\022\026"
          + "BuildOperationMetadata\022\237\001\n\010GetBuild\022..go"
          + "ogle.devtools.cloudbuild.v1.GetBuildRequ"
          + "est\032$.google.devtools.cloudbuild.v1.Buil"
          + "d\"=\202\323\344\223\002\'\022%/v1/projects/{project_id}/bui"
          + "lds/{id}\332A\rproject_id,id\022\257\001\n\nListBuilds\022"
          + "0.google.devtools.cloudbuild.v1.ListBuil"
          + "dsRequest\0321.google.devtools.cloudbuild.v"
          + "1.ListBuildsResponse\"<\202\323\344\223\002\"\022 /v1/projec"
          + "ts/{project_id}/builds\332A\021project_id,filt"
          + "er\022\257\001\n\013CancelBuild\0221.google.devtools.clo"
          + "udbuild.v1.CancelBuildRequest\032$.google.d"
          + "evtools.cloudbuild.v1.Build\"G\202\323\344\223\0021\",/v1"
          + "/projects/{project_id}/builds/{id}:cance"
          + "l:\001*\332A\rproject_id,id\022\307\001\n\nRetryBuild\0220.go"
          + "ogle.devtools.cloudbuild.v1.RetryBuildRe"
          + "quest\032\035.google.longrunning.Operation\"h\202\323"
          + "\344\223\0020\"+/v1/projects/{project_id}/builds/{"
          + "id}:retry:\001*\332A\rproject_id,id\312A\037\n\005Build\022\026"
          + "BuildOperationMetadata\022\305\001\n\022CreateBuildTr"
          + "igger\0228.google.devtools.cloudbuild.v1.Cr"
          + "eateBuildTriggerRequest\032+.google.devtool"
          + "s.cloudbuild.v1.BuildTrigger\"H\202\323\344\223\002-\"\"/v"
          + "1/projects/{project_id}/triggers:\007trigge"
          + "r\332A\022project_id,trigger\022\306\001\n\017GetBuildTrigg"
          + "er\0225.google.devtools.cloudbuild.v1.GetBu"
          + "ildTriggerRequest\032+.google.devtools.clou"
          + "dbuild.v1.BuildTrigger\"O\202\323\344\223\0021\022//v1/proj"
          + "ects/{project_id}/triggers/{trigger_id}\332"
          + "A\025project_id,trigger_id\022\277\001\n\021ListBuildTri"
          + "ggers\0227.google.devtools.cloudbuild.v1.Li"
          + "stBuildTriggersRequest\0328.google.devtools"
          + ".cloudbuild.v1.ListBuildTriggersResponse"
          + "\"7\202\323\344\223\002$\022\"/v1/projects/{project_id}/trig"
          + "gers\332A\nproject_id\022\267\001\n\022DeleteBuildTrigger"
          + "\0228.google.devtools.cloudbuild.v1.DeleteB"
          + "uildTriggerRequest\032\026.google.protobuf.Emp"
          + "ty\"O\202\323\344\223\0021*//v1/projects/{project_id}/tr"
          + "iggers/{trigger_id}\332A\025project_id,trigger"
          + "_id\022\335\001\n\022UpdateBuildTrigger\0228.google.devt"
          + "ools.cloudbuild.v1.UpdateBuildTriggerReq"
          + "uest\032+.google.devtools.cloudbuild.v1.Bui"
          + "ldTrigger\"`\202\323\344\223\002:2//v1/projects/{project"
          + "_id}/triggers/{trigger_id}:\007trigger\332A\035pr"
          + "oject_id,trigger_id,trigger\022\356\001\n\017RunBuild"
          + "Trigger\0225.google.devtools.cloudbuild.v1."
          + "RunBuildTriggerRequest\032\035.google.longrunn"
          + "ing.Operation\"\204\001\202\323\344\223\002=\"3/v1/projects/{pr"
          + "oject_id}/triggers/{trigger_id}:run:\006sou"
          + "rce\332A\034project_id,trigger_id,source\312A\037\n\005B"
          + "uild\022\026BuildOperationMetadata\032M\312A\031cloudbu"
          + "ild.googleapis.com\322A.https://www.googlea"
          + "pis.com/auth/cloud-platformB\206\001\n\030com.goog"
          + "le.cloudbuild.v1P\001ZGgoogle.golang.org/ge"
          + "nproto/googleapis/devtools/cloudbuild/v1"
          + ";cloudbuild\242\002\003GCB\352\002\030Google::Cloud::Build"
          + "::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_devtools_cloudbuild_v1_RetryBuildRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_RetryBuildRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_RetryBuildRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Id",
            });
    internal_static_google_devtools_cloudbuild_v1_RunBuildTriggerRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_devtools_cloudbuild_v1_RunBuildTriggerRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_RunBuildTriggerRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "TriggerId", "Source",
            });
    internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_devtools_cloudbuild_v1_StorageSource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_StorageSource_descriptor,
            new java.lang.String[] {
              "Bucket", "Object", "Generation",
            });
    internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_devtools_cloudbuild_v1_RepoSource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor,
            new java.lang.String[] {
              "ProjectId",
              "RepoName",
              "BranchName",
              "TagName",
              "CommitSha",
              "Dir",
              "InvertRegex",
              "Substitutions",
              "Revision",
            });
    internal_static_google_devtools_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_RepoSource_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_RepoSource_SubstitutionsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_Source_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_devtools_cloudbuild_v1_Source_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Source_descriptor,
            new java.lang.String[] {
              "StorageSource", "RepoSource", "Source",
            });
    internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_devtools_cloudbuild_v1_BuiltImage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuiltImage_descriptor,
            new java.lang.String[] {
              "Name", "Digest", "PushTiming",
            });
    internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_devtools_cloudbuild_v1_BuildStep_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuildStep_descriptor,
            new java.lang.String[] {
              "Name",
              "Env",
              "Args",
              "Dir",
              "Id",
              "WaitFor",
              "Entrypoint",
              "SecretEnv",
              "Volumes",
              "Timing",
              "PullTiming",
              "Timeout",
              "Status",
            });
    internal_static_google_devtools_cloudbuild_v1_Volume_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_devtools_cloudbuild_v1_Volume_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Volume_descriptor,
            new java.lang.String[] {
              "Name", "Path",
            });
    internal_static_google_devtools_cloudbuild_v1_Results_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_devtools_cloudbuild_v1_Results_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Results_descriptor,
            new java.lang.String[] {
              "Images",
              "BuildStepImages",
              "ArtifactManifest",
              "NumArtifacts",
              "BuildStepOutputs",
              "ArtifactTiming",
            });
    internal_static_google_devtools_cloudbuild_v1_ArtifactResult_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_devtools_cloudbuild_v1_ArtifactResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_ArtifactResult_descriptor,
            new java.lang.String[] {
              "Location", "FileHash",
            });
    internal_static_google_devtools_cloudbuild_v1_Build_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_devtools_cloudbuild_v1_Build_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Build_descriptor,
            new java.lang.String[] {
              "Id",
              "ProjectId",
              "Status",
              "StatusDetail",
              "Source",
              "Steps",
              "Results",
              "CreateTime",
              "StartTime",
              "FinishTime",
              "Timeout",
              "Images",
              "QueueTtl",
              "Artifacts",
              "LogsBucket",
              "SourceProvenance",
              "BuildTriggerId",
              "Options",
              "LogUrl",
              "Substitutions",
              "Tags",
              "Secrets",
              "Timing",
              "ServiceAccount",
            });
    internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_Build_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Build_SubstitutionsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_Build_TimingEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_Build_descriptor.getNestedTypes().get(1);
    internal_static_google_devtools_cloudbuild_v1_Build_TimingEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Build_TimingEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_Artifacts_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_devtools_cloudbuild_v1_Artifacts_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Artifacts_descriptor,
            new java.lang.String[] {
              "Images", "Objects",
            });
    internal_static_google_devtools_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor =
        internal_static_google_devtools_cloudbuild_v1_Artifacts_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_Artifacts_ArtifactObjects_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor,
            new java.lang.String[] {
              "Location", "Paths", "Timing",
            });
    internal_static_google_devtools_cloudbuild_v1_TimeSpan_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_devtools_cloudbuild_v1_TimeSpan_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_TimeSpan_descriptor,
            new java.lang.String[] {
              "StartTime", "EndTime",
            });
    internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuildOperationMetadata_descriptor,
            new java.lang.String[] {
              "Build",
            });
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor,
            new java.lang.String[] {
              "ResolvedStorageSource", "ResolvedRepoSource", "FileHashes",
            });
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_SourceProvenance_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_devtools_cloudbuild_v1_FileHashes_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_FileHashes_descriptor,
            new java.lang.String[] {
              "FileHash",
            });
    internal_static_google_devtools_cloudbuild_v1_Hash_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_devtools_cloudbuild_v1_Hash_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Hash_descriptor,
            new java.lang.String[] {
              "Type", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_Secret_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_devtools_cloudbuild_v1_Secret_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Secret_descriptor,
            new java.lang.String[] {
              "KmsKeyName", "SecretEnv",
            });
    internal_static_google_devtools_cloudbuild_v1_Secret_SecretEnvEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_Secret_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_cloudbuild_v1_Secret_SecretEnvEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_Secret_SecretEnvEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_CreateBuildRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Build",
            });
    internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_GetBuildRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Id",
            });
    internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_ListBuildsRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "PageSize", "PageToken", "Filter",
            });
    internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_ListBuildsResponse_descriptor,
            new java.lang.String[] {
              "Builds", "NextPageToken",
            });
    internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_CancelBuildRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Id",
            });
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor,
            new java.lang.String[] {
              "Id",
              "Description",
              "Name",
              "Tags",
              "TriggerTemplate",
              "Github",
              "Build",
              "Filename",
              "CreateTime",
              "Disabled",
              "Substitutions",
              "IgnoredFiles",
              "IncludedFiles",
              "BuildTemplate",
            });
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor =
        internal_static_google_devtools_cloudbuild_v1_BuildTrigger_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuildTrigger_SubstitutionsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_devtools_cloudbuild_v1_GitHubEventsConfig_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_devtools_cloudbuild_v1_GitHubEventsConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_GitHubEventsConfig_descriptor,
            new java.lang.String[] {
              "InstallationId", "Owner", "Name", "PullRequest", "Push", "Event",
            });
    internal_static_google_devtools_cloudbuild_v1_PullRequestFilter_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_devtools_cloudbuild_v1_PullRequestFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_PullRequestFilter_descriptor,
            new java.lang.String[] {
              "Branch", "CommentControl", "InvertRegex", "GitRef",
            });
    internal_static_google_devtools_cloudbuild_v1_PushFilter_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_devtools_cloudbuild_v1_PushFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_PushFilter_descriptor,
            new java.lang.String[] {
              "Branch", "Tag", "InvertRegex", "GitRef",
            });
    internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_CreateBuildTriggerRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Trigger",
            });
    internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_GetBuildTriggerRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "TriggerId",
            });
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "PageSize", "PageToken",
            });
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_ListBuildTriggersResponse_descriptor,
            new java.lang.String[] {
              "Triggers", "NextPageToken",
            });
    internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_DeleteBuildTriggerRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "TriggerId",
            });
    internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_UpdateBuildTriggerRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "TriggerId", "Trigger",
            });
    internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor =
        getDescriptor().getMessageTypes().get(33);
    internal_static_google_devtools_cloudbuild_v1_BuildOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_devtools_cloudbuild_v1_BuildOptions_descriptor,
            new java.lang.String[] {
              "SourceProvenanceHash",
              "RequestedVerifyOption",
              "MachineType",
              "DiskSizeGb",
              "SubstitutionOption",
              "DynamicSubstitutions",
              "LogStreamingOption",
              "WorkerPool",
              "Logging",
              "Env",
              "SecretEnv",
              "Volumes",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
